[project]
name = "stacksbuilder-contracts"
description = "Smart contracts for the StacksBuilder platform"
authors = ["StacksBuilder Team"]
telemetry = false
cache_dir = "./.clarinet"

[contracts.developer-profiles]
path = "contracts/developer-profiles.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

# Network configurations
[networks.testnet]
stacks_node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
bitcoin_node_rpc_address = "https://blockstream.info/testnet/api"
bitcoin_node_p2p_address = "bitcoin-testnet.blockdaemon.com:1024"

[networks.mainnet]
stacks_node_rpc_address = "https://stacks-node-api.mainnet.stacks.co"
bitcoin_node_rpc_address = "https://blockstream.info/api"
bitcoin_node_p2p_address = "bitcoin-mainnet.blockdaemon.com:1024"

# Deployment settings
[deployments.testnet]
network = "testnet"
stacks_node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
bitcoin_node_rpc_address = "https://blockstream.info/testnet/api"

[deployments.mainnet]
network = "mainnet"
stacks_node_rpc_address = "https://stacks-node-api.mainnet.stacks.co"
bitcoin_node_rpc_address = "https://blockstream.info/api"
